### ISSUE TITLE
[학습노트] Django TestCase  구조 

### ISSUE THREAD

**Issue by KimSoungRyoul** [rgpkr-tech-intern-1st/KimSoungRyoulRepo#9]
# TestCase 상속 구조

<img width="462" alt="2018-09-19 11 20 18" src="https://user-images.githubusercontent.com/24240623/45727285-04b72980-bbfe-11e8-8440-705c978c9167.png">

    UserTest(TestCase):
         def test1():

### 장고는 테스트 케이스를 실행하는데 commit넣지 않고 테스트 끝나면 rollback 해버리는 것을 기본으로하고있다

    @Test
    @Transactional
    public void test1(){
    }

### SetUp
1. 단위테스팅 한번 실행할때 마다 한번씩 실행 

### SetUpClass
1. 클래스 실행시 최초 1회 실행 

### SetUpTestData
1. SetUpClasss 처럼 최초 1회 실행하지만 Transactions이 지원안됨 즉 ! TestClass 내부 더미데이터 넣을때 여기에 넣으면 모든 테스트 케이스에서 더미데이터가 살아있음

2. 겨

**Comment by falsetru** [comment]
- 이슈보다는 위키에 정리하는게 좋을듯합니다.
- 내용이 잘린듯합니다.

**Comment by KimSoungRyoul** [comment]
@falsetru 넵 감사합니다 내용 잘린거는 작성중인데 ok를 잘못눌었나봐요
